spring:
  datasource:
    url: jdbc:mysql://my-db01.mysql.database.azure.com:3306/boarddb?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul
    username: user01
    password: tkatjd12#$56
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MyBatis 사용 중이므로 JPA 자동 DDL 비활성화
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
