spring:
  datasource:
    url: jdbc:mysql://my-db01.mysql.database.azure.com:3306/boarddb?useSSL=true&requireSSL=true&verifyServerCertificate=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: user01
    password: tkatjd12#$56
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
